name: source_package

on: push

jobs:
  
  core-macos10_15:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Setup Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.10
      - run: python --version
      - run: python3-config --prefix
      - run: python3 --version
      - run: mkdir build && cd build && cmake ..
