name: source_package

on: push

jobs:
  
  core-macos11:
    runs-on: macos-11
    steps:
      - run: |
          git clone https://github.com/coin-or/Osi.git
          cd Osi && ./configure
      - run: pkg-config
      - uses: actions/checkout@v2.4.0
      - name: Setup Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.9
      - run: python --version
      - run: python3-config --prefix
      - run: python3 --version
      - run: mkdir build && cd build && cmake ..
