name: source_package

on: push

jobs:
  
  core-macos10_15:
    runs-on: macos-10.15
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.5
      - run: python --version
      - run: cat /usr/local/bin/python-config
      - run: python-config --prefix
      - run: python3 --version

